# Generated by Django 3.2.4 on 2021-07-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_statement_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='likes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statement',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
