# Generated by Django 3.2.4 on 2021-07-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0003_auto_20210705_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='sub_title',
            field=models.TextField(default='N/A'),
        ),
    ]
